name: generate-3d-contrib

on:
  schedule:
    - cron: "0 18 * * *" # tiap hari jam 01:00 WIB
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate 3D contribution graph
        uses: yoshi389111/github-profile-3d-contrib@0.9.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: Big-com18
          SETTING_JSON: 3d-contrib-settings.json

      - name: Push to output branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A profile-3d-contrib
          git commit -m "update 3d contribution graph" || exit 0
          git push origin HEAD:output --force
